[tool.poetry]
name = "todo-app"
version = "0.1.0"
description = ""
authors = ["dotory-60 <busdotory@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
